const jwt = require('jsonwebtoken');

// Mock payload like the one generated by auth.service.ts
const payload = {
  utilisateur: {
    id: "6937ff...something",
    nom: "RP_Goma",
    profil: "RP",
    pays: null, // WAIT, if the user didn't have pays populated at login?
  }
};
console.log(payload);
