import json

def set_nested(d, key_path, value):
    keys = key_path.split('.')
    current = d
    for i, k in enumerate(keys[:-1]):
        if k not in current:
            current[k] = {}
        current = current[k]
    current[keys[-1]] = value

# The keys we used in HTML
menus_fr = {
    "MENU.FLEET_MAINTENANCE": "Flotte & Maintenance",
    "MENU.MAINTENANCE_PLAN": "Plan de Maintenance",
    "MENU.ENERGY": "Énergie",
    "MENU.GENERATORS_LIST": "Liste des Générateurs",
    "MENU.GENERATOR_LOGBOOK": "Logbook Générateur",
    "MENU.SECURITY": "Sécurité",
    "MENU.FLEET_SETTINGS": "Paramétrages Fleet",
    "MENU.VEHICLE_TYPES": "Types de véhicules",
    "MENU.CO2_FACTORS": "Facteurs CO2",
    "MENU.MAINTENANCE_MANAGEMENT": "Gestion des Maintenances",
    "MENU.INTERVAL_CONFIG": "Configuration Intervalles",
    "MENU.SERVICE_TYPES": "Type de service",
    "MENU.SYSTEM_SETTINGS": "Paramètres Système",
    "MENU.GENERAL_CONFIG": "Configuration Générale",
    "MENU.WORKFLOW_VISUALIZATION": "Workflow Visualisation",
    "MENU.APP_ROADMAP_SECURITY": "Roadmap et sécurité de l'APP",
    "MENU.ACTIVITY_LOG": "Journal d'activité",
    "MENU.PROFILE_MATRIX": "Matrice des Profils (RBAC)",
    "MENU.USER_GUIDE": "Guide Utilisateur"
}

menus_en = {
    "MENU.FLEET_MAINTENANCE": "Fleet & Maintenance",
    "MENU.MAINTENANCE_PLAN": "Maintenance Plan",
    "MENU.ENERGY": "Energy",
    "MENU.GENERATORS_LIST": "Generators List",
    "MENU.GENERATOR_LOGBOOK": "Generator Logbook",
    "MENU.SECURITY": "Security",
    "MENU.FLEET_SETTINGS": "Fleet Settings",
    "MENU.VEHICLE_TYPES": "Vehicle Types",
    "MENU.CO2_FACTORS": "CO2 Factors",
    "MENU.MAINTENANCE_MANAGEMENT": "Maintenance Management",
    "MENU.INTERVAL_CONFIG": "Interval Configuration",
    "MENU.SERVICE_TYPES": "Service Types",
    "MENU.SYSTEM_SETTINGS": "System Settings",
    "MENU.GENERAL_CONFIG": "General Configuration",
    "MENU.WORKFLOW_VISUALIZATION": "Workflow Visualization",
    "MENU.APP_ROADMAP_SECURITY": "App Roadmap & Security",
    "MENU.ACTIVITY_LOG": "Activity Log",
    "MENU.PROFILE_MATRIX": "Profile Matrix (RBAC)",
    "MENU.USER_GUIDE": "User Guide"
}

guide_fr = {
    "USER_GUIDE.TITLE": "Guide Utilisateur FleetTrack",
    "USER_GUIDE.VERSION": "Version 2.14 - Février 2026",
    "USER_GUIDE.TOC.TITLE": "Table des Matières",
    "USER_GUIDE.TOC.INTRO": "Introduction",
    "USER_GUIDE.TOC.ACCESS": "Accès aux Applications",
    "USER_GUIDE.TOC.WEB": "Interface Web",
    "USER_GUIDE.TOC.MOBILE": "E-Logbook Mobile (PWA)",
    "USER_GUIDE.TOC.FAQ": "FAQ et Dépannage",
    "USER_GUIDE.INTRO.TITLE": "Introduction",
    "USER_GUIDE.INTRO.P1_1": "FleetTrack est la solution de gestion de flotte optimisée pour l'organisation. Elle repose sur une",
    "USER_GUIDE.INTRO.P1_2": "architecture multi-pays stricte",
    "USER_GUIDE.INTRO.BULLET1_1": "Cloisonnement des données :",
    "USER_GUIDE.INTRO.BULLET1_2": "Un utilisateur affecté à un pays ne peut voir QUE les données de ce pays.",
    "USER_GUIDE.INTRO.BULLET2_1": "Exception SuperAdmin :",
    "USER_GUIDE.INTRO.BULLET2_2": "Seul le rôle SuperAdmin possède une vue globale.",
    "USER_GUIDE.INTRO.NOTE_TITLE": "Important :",
    "USER_GUIDE.INTRO.NOTE_DESC": "L'application est divisée en deux interfaces connectées :",
    "USER_GUIDE.INTRO.NOTE_BULLET1_1": "Interface Web (Admin) :",
    "USER_GUIDE.INTRO.NOTE_BULLET1_2": "Gestion, Planification, Validation par le bureau.",
    "USER_GUIDE.INTRO.NOTE_BULLET2_1": "E-Logbook (Chauffeur) :",
    "USER_GUIDE.INTRO.NOTE_BULLET2_2": "Application Mobile (PWA) pour le terrain.",
    "USER_GUIDE.ROLES.TITLE": "Rôles Utilisateurs",
    "USER_GUIDE.ROLES.COL1": "Rôle",
    "USER_GUIDE.ROLES.COL2": "Accès",
    "USER_GUIDE.ROLES.COL3": "Portée (Scope)",
    "USER_GUIDE.ROLES.COL4": "Responsabilités",
    "USER_GUIDE.ROLES.ROW1_1": "SuperAdmin",
    "USER_GUIDE.ROLES.ROW1_2": "Web (Complet)",
    "USER_GUIDE.ROLES.ROW1_3": "🌍 Monde (Tous Pays)",
    "USER_GUIDE.ROLES.ROW1_4": "Configuration système, audit global.",
    "USER_GUIDE.ROLES.ROW2_1": "Admin (Pays)",
    "USER_GUIDE.ROLES.ROW2_2": "Web (Pays)",
    "USER_GUIDE.ROLES.ROW2_3": "🏳️ Pays (Mission)",
    "USER_GUIDE.ROLES.ROW2_4": "Gestion de TOUTES les bases de sa mission.",
    "USER_GUIDE.ROLES.ROW3_1": "Superviseur (Base)",
    "USER_GUIDE.ROLES.ROW3_2": "Web (Base)",
    "USER_GUIDE.ROLES.ROW3_3": "📍 Base Locale",
    "USER_GUIDE.ROLES.ROW3_4": "Validation hiérarchique, suivi maintenance.",
    "USER_GUIDE.ROLES.ROW4_1": "Superviseur Sécurité",
    "USER_GUIDE.ROLES.ROW4_2": "Web (Base/Pays)",
    "USER_GUIDE.ROLES.ROW4_3": "🛡️ Transverse",
    "USER_GUIDE.ROLES.ROW4_4": "Validation sécuritaire des mouvements.",
    "USER_GUIDE.ROLES.ROW5_1": "Demandeur",
    "USER_GUIDE.ROLES.ROW5_2": "Web (Restreint)",
    "USER_GUIDE.ROLES.ROW5_3": "👤 Personnel",
    "USER_GUIDE.ROLES.ROW5_4": "Création de demandes de mouvements.",
    "USER_GUIDE.ROLES.ROW6_1": "Chauffeur",
    "USER_GUIDE.ROLES.ROW6_2": "Mobile PWA",
    "USER_GUIDE.ROLES.ROW6_3": "🚙 Véhicule",
    "USER_GUIDE.ROLES.ROW6_4": "Tenue du carnet de bord.",
    "USER_GUIDE.ACCESS.TITLE": "Accès aux Applications",
    "USER_GUIDE.ACCESS.WEB_TITLE": "Interface Web",
    "USER_GUIDE.ACCESS.URL": "URL",
    "USER_GUIDE.ACCESS.BROWSERS": "Navigateurs compatibles",
    "USER_GUIDE.ACCESS.BROWSERS_DESC": "Chrome (recommandé), Firefox, Edge, Safari",
    "USER_GUIDE.ACCESS.MOBILE_TITLE": "E-Logbook Mobile (PWA)",
    "USER_GUIDE.ACCESS.MOBILE_DESC_1": "Ouvrez l'URL sur votre téléphone et choisissez",
    "USER_GUIDE.ACCESS.MOBILE_DESC_2": "Ajouter à l'écran d'accueil",
    "USER_GUIDE.ACCESS.MOBILE_DESC_3": "pour l'utiliser comme une application native.",
    "USER_GUIDE.WEB.TITLE": "Interface Web",
    "USER_GUIDE.WEB.PLANNING.TITLE": "Planning Global",
    "USER_GUIDE.WEB.PLANNING.DESC": "Le cœur opérationnel. Visualisez tous les mouvements de la semaine d'un coup d'œil.",
    "USER_GUIDE.WEB.NEW_FEATURES": "Nouveautés :",
    "USER_GUIDE.WEB.PLANNING.FEAT1_1": "Drag & Drop :",
    "USER_GUIDE.WEB.PLANNING.FEAT1_2": "Assignez un véhicule en glissant la demande.",
    "USER_GUIDE.WEB.PLANNING.FEAT2_1": "Mode Inbox :",
    "USER_GUIDE.WEB.PLANNING.FEAT2_2": "Les notifications non lues en priorité.",
    "USER_GUIDE.WEB.DRIVER_PLANNING.TITLE": "Disponibilité des Chauffeurs",
    "USER_GUIDE.WEB.NEW_FEATURE_TAG": "Nouveau",
    "USER_GUIDE.WEB.DRIVER_PLANNING.DESC": "Un planning dédié pour gérer le temps de travail des chauffeurs.",
    "USER_GUIDE.WEB.DRIVER_PLANNING.BULLET1_1": "Planning :",
    "USER_GUIDE.WEB.DRIVER_PLANNING.BULLET1_2": "Ajout des indisponibilités (Congés, Maladie, Repos).",
    "USER_GUIDE.WEB.DRIVER_PLANNING.BULLET2_1": "Validation :",
    "USER_GUIDE.WEB.DRIVER_PLANNING.BULLET2_2": "Un chauffeur indisponible ne peut pas être assigné.",
    "USER_GUIDE.WEB.ROADMAP.TITLE": "Vision & Sécurité (Roadmap)",
    "USER_GUIDE.WEB.NEW_MENU_TAG": "Nouveau Menu",
    "USER_GUIDE.WEB.ROADMAP.DESC": "Une transparence totale sur l'évolution de l'outil et sa sécurité.",
    "USER_GUIDE.WEB.ROADMAP.BULLET1_1": "Roadmap :",
    "USER_GUIDE.WEB.ROADMAP.BULLET1_2": "Consultez les prochaines fonctionnalités.",
    "USER_GUIDE.WEB.ROADMAP.BULLET2_1": "Changelog :",
    "USER_GUIDE.WEB.ROADMAP.BULLET2_2": "Historique des mises à jour.",
    "USER_GUIDE.WEB.ROADMAP.BULLET3_1": "Sécurité :",
    "USER_GUIDE.WEB.ROADMAP.BULLET3_2": "Détails techniques (RGPD, Chiffrement).",
    "USER_GUIDE.WEB.ECO.TITLE": "Objectifs Environnementaux",
    "USER_GUIDE.WEB.ECO.DESC": "Suivez l'empreinte carbone de la flotte.",
    "USER_GUIDE.WEB.ECO.BULLET1_1": "IAP :",
    "USER_GUIDE.WEB.ECO.BULLET1_2": "Indicateur d'Activité Pondéré.",
    "USER_GUIDE.WEB.ECO.BULLET2_1": "Plan d'Action :",
    "USER_GUIDE.WEB.ECO.BULLET2_2": "Suivi des objectifs de réduction CO2.",
    "USER_GUIDE.WEB.ALERTS.TITLE": "Alertes de Sécurité",
    "USER_GUIDE.WEB.ALERTS.DESC": "Permet d'envoyer des notifications urgentes (Web Push).",
    "USER_GUIDE.WEB.ALERTS.BULLET1": "Ciblez un véhicule précis ou TOUTE LA FLOTTE.",
    "USER_GUIDE.WEB.ALERTS.BULLET2": "Le chauffeur reçoit l'alerte même si l'App est fermée.",
    "USER_GUIDE.WEB.VALIDATION.TITLE": "Validation & Consolidation",
    "USER_GUIDE.WEB.VALIDATION.DESC": "Le workflow de validation :",
    "USER_GUIDE.WEB.VALIDATION.STEP1_1": "Logistique :",
    "USER_GUIDE.WEB.VALIDATION.STEP1_2": "Vérifie la disponibilité.",
    "USER_GUIDE.WEB.VALIDATION.STEP2_1": "Sécurité :",
    "USER_GUIDE.WEB.VALIDATION.STEP2_2": "Valide la faisabilité (Zones à risques).",
    "USER_GUIDE.WEB.NEW_PROCESS": "Nouveautés du processus :",
    "USER_GUIDE.WEB.VALIDATION.NEW1_1": "Validation Parallèle :",
    "USER_GUIDE.WEB.VALIDATION.NEW1_2": "Validation indépendante et simultanée.",
    "USER_GUIDE.WEB.VALIDATION.NEW2_1": "Validation en Cascade :",
    "USER_GUIDE.WEB.VALIDATION.NEW2_2": "Validation par les niveaux de sécurité inférieurs requise.",
    "USER_GUIDE.WEB.VALIDATION.CONSO1": "Utilisez la",
    "USER_GUIDE.WEB.VALIDATION.CONSO2": "Consolidation",
    "USER_GUIDE.WEB.VALIDATION.CONSO3": "pour grouper plusieurs demandes.",
    "USER_GUIDE.WEB.MAINTENANCE.TITLE": "Gestion de Flotte & Maintenance",
    "USER_GUIDE.WEB.MAINTENANCE.TIP_TITLE": "Notifications :",
    "USER_GUIDE.WEB.MAINTENANCE.TIP_DESC": "Email automatique au superviseur si maintenance imminente.",
    "USER_GUIDE.WEB.MAINTENANCE.BULLET1_1": "Suivi Hebdo :",
    "USER_GUIDE.WEB.MAINTENANCE.BULLET1_2": "Checklists chauffeurs.",
    "USER_GUIDE.WEB.MAINTENANCE.BULLET2_1": "Configuration :",
    "USER_GUIDE.WEB.MAINTENANCE.BULLET2_2": "Définissez vos intervalles.",
    "USER_GUIDE.WEB.GENERATORS.TITLE": "Maintenance des Générateurs",
    "USER_GUIDE.WEB.GENERATORS.DESC": "Gestion et suivi des générateurs de l'organisation.",
    "USER_GUIDE.WEB.GENERATORS.BULLET1_1": "Logbook :",
    "USER_GUIDE.WEB.GENERATORS.BULLET1_2": "Carnet d'entretien et pannes.",
    "USER_GUIDE.WEB.GENERATORS.BULLET2_1": "Plan de Maintenance :",
    "USER_GUIDE.WEB.GENERATORS.BULLET2_2": "Suivi des heures de fonctionnement (Run Hours).",
    "USER_GUIDE.WEB.REPORTS.TITLE": "Rapports & Analytics",
    "USER_GUIDE.WEB.REPORTS.DESC": "Exportez vos rapports mensuels en un clic.",
    "USER_GUIDE.MOBILE.TITLE": "E-Logbook Mobile (PWA)",
    "USER_GUIDE.MOBILE.OFFLINE_TITLE": "Mode Hors-Ligne :",
    "USER_GUIDE.MOBILE.OFFLINE_DESC": "L'application fonctionne ENTIÈREMENT sans connexion.",
    "USER_GUIDE.MOBILE.PUSH.TITLE": "Notifications Web Push",
    "USER_GUIDE.MOBILE.PUSH.DESC": "Pour la sécurité et la réactivité :",
    "USER_GUIDE.MOBILE.PUSH.BULLET1_1": "App Fermée :",
    "USER_GUIDE.MOBILE.PUSH.BULLET1_2": "Vous recevez les alertes en arrière-plan.",
    "USER_GUIDE.MOBILE.PUSH.BULLET2_1": "Activation :",
    "USER_GUIDE.MOBILE.PUSH.BULLET2_2": "Autorisez les notifications dans l'Inbox.",
    "USER_GUIDE.MOBILE.DAILY.TITLE": "Utilisation Quotidienne",
    "USER_GUIDE.MOBILE.DAILY.BULLET1_1": "Sélection Véhicule :",
    "USER_GUIDE.MOBILE.DAILY.BULLET1_2": "Choisissez votre véhicule au démarrage.",
    "USER_GUIDE.MOBILE.DAILY.BULLET2_1": "GPS Automatique :",
    "USER_GUIDE.MOBILE.DAILY.BULLET2_2": "Enregistrement de la position.",
    "USER_GUIDE.MOBILE.DAILY.BULLET3_1": "Mode Libre :",
    "USER_GUIDE.MOBILE.DAILY.BULLET3_2": "Trajets Ad-Hoc sans demande préalable.",
    "USER_GUIDE.MOBILE.INCIDENTS.TITLE": "Services & Incidents",
    "USER_GUIDE.MOBILE.INCIDENTS.BULLET1_1": "Maintenance :",
    "USER_GUIDE.MOBILE.INCIDENTS.BULLET1_2": "Cochez les tâches réalisées.",
    "USER_GUIDE.MOBILE.INCIDENTS.BULLET2_1": "Incidents :",
    "USER_GUIDE.MOBILE.INCIDENTS.BULLET2_2": "Déclarez accidents avec photos.",
    "USER_GUIDE.FAQ.TITLE": "FAQ et Dépannage",
    "USER_GUIDE.FAQ.Q1": "Q : Le manuel PDF ne s'ouvre pas à la bonne page ?",
    "USER_GUIDE.FAQ.A1": "R : Vérifiez la configuration du Template.",
    "USER_GUIDE.FAQ.SUPPORT": "Support Technique :",
    "USER_GUIDE.FAQ.SUPPORT_NO_EMAIL": "Veuillez contacter votre administrateur système local pour toute assistance.",
    "USER_GUIDE.FOOTER": "Tous droits réservés"
}

guide_en = {
    "USER_GUIDE.TITLE": "FleetTrack User Guide",
    "USER_GUIDE.VERSION": "Version 2.14 - February 2026",
    "USER_GUIDE.TOC.TITLE": "Table of Contents",
    "USER_GUIDE.TOC.INTRO": "Introduction",
    "USER_GUIDE.TOC.ACCESS": "Application Access",
    "USER_GUIDE.TOC.WEB": "Web Interface",
    "USER_GUIDE.TOC.MOBILE": "Mobile E-Logbook (PWA)",
    "USER_GUIDE.TOC.FAQ": "FAQ & Troubleshooting",
    "USER_GUIDE.INTRO.TITLE": "Introduction",
    "USER_GUIDE.INTRO.P1_1": "FleetTrack is the optimized fleet management solution for the organization. It uses a",
    "USER_GUIDE.INTRO.P1_2": "strict multi-country architecture",
    "USER_GUIDE.INTRO.BULLET1_1": "Data Isolation:",
    "USER_GUIDE.INTRO.BULLET1_2": "A user assigned to a country can ONLY see that country's data.",
    "USER_GUIDE.INTRO.BULLET2_1": "SuperAdmin Exception:",
    "USER_GUIDE.INTRO.BULLET2_2": "Only the SuperAdmin role has a global view.",
    "USER_GUIDE.INTRO.NOTE_TITLE": "Important:",
    "USER_GUIDE.INTRO.NOTE_DESC": "The application is divided into two connected interfaces:",
    "USER_GUIDE.INTRO.NOTE_BULLET1_1": "Web Interface (Admin):",
    "USER_GUIDE.INTRO.NOTE_BULLET1_2": "Management, Planning, Validation by the office.",
    "USER_GUIDE.INTRO.NOTE_BULLET2_1": "E-Logbook (Driver):",
    "USER_GUIDE.INTRO.NOTE_BULLET2_2": "Mobile application (PWA) for the field.",
    "USER_GUIDE.ROLES.TITLE": "User Roles",
    "USER_GUIDE.ROLES.COL1": "Role",
    "USER_GUIDE.ROLES.COL2": "Access",
    "USER_GUIDE.ROLES.COL3": "Scope",
    "USER_GUIDE.ROLES.COL4": "Responsibilities",
    "USER_GUIDE.ROLES.ROW1_1": "SuperAdmin",
    "USER_GUIDE.ROLES.ROW1_2": "Web (Full)",
    "USER_GUIDE.ROLES.ROW1_3": "🌍 Global",
    "USER_GUIDE.ROLES.ROW1_4": "System configuration, global audit.",
    "USER_GUIDE.ROLES.ROW2_1": "Admin (Country)",
    "USER_GUIDE.ROLES.ROW2_2": "Web (Country)",
    "USER_GUIDE.ROLES.ROW2_3": "🏳️ Country",
    "USER_GUIDE.ROLES.ROW2_4": "Management of ALL bases in the mission.",
    "USER_GUIDE.ROLES.ROW3_1": "Supervisor (Base)",
    "USER_GUIDE.ROLES.ROW3_2": "Web (Base)",
    "USER_GUIDE.ROLES.ROW3_3": "📍 Local Base",
    "USER_GUIDE.ROLES.ROW3_4": "Hierarchical validation, maintenance tracking.",
    "USER_GUIDE.ROLES.ROW4_1": "Security Supervisor",
    "USER_GUIDE.ROLES.ROW4_2": "Web (Base/Country)",
    "USER_GUIDE.ROLES.ROW4_3": "🛡️ Transverse",
    "USER_GUIDE.ROLES.ROW4_4": "Security validation for movements.",
    "USER_GUIDE.ROLES.ROW5_1": "Requester",
    "USER_GUIDE.ROLES.ROW5_2": "Web (Restricted)",
    "USER_GUIDE.ROLES.ROW5_3": "👤 Personal",
    "USER_GUIDE.ROLES.ROW5_4": "Movement request creation.",
    "USER_GUIDE.ROLES.ROW6_1": "Driver",
    "USER_GUIDE.ROLES.ROW6_2": "Mobile PWA",
    "USER_GUIDE.ROLES.ROW6_3": "🚙 Vehicle",
    "USER_GUIDE.ROLES.ROW6_4": "Logbook entry.",
    "USER_GUIDE.ACCESS.TITLE": "Application Access",
    "USER_GUIDE.ACCESS.WEB_TITLE": "Web Interface",
    "USER_GUIDE.ACCESS.URL": "URL",
    "USER_GUIDE.ACCESS.BROWSERS": "Supported Browsers",
    "USER_GUIDE.ACCESS.BROWSERS_DESC": "Chrome (recommended), Firefox, Edge, Safari",
    "USER_GUIDE.ACCESS.MOBILE_TITLE": "Mobile E-Logbook (PWA)",
    "USER_GUIDE.ACCESS.MOBILE_DESC_1": "Open the URL on your phone and choose",
    "USER_GUIDE.ACCESS.MOBILE_DESC_2": "Add to Home Screen",
    "USER_GUIDE.ACCESS.MOBILE_DESC_3": "to use it as a native application.",
    "USER_GUIDE.WEB.TITLE": "Web Interface",
    "USER_GUIDE.WEB.PLANNING.TITLE": "Global Planning",
    "USER_GUIDE.WEB.PLANNING.DESC": "The operational core. View all movements for the week at a glance.",
    "USER_GUIDE.WEB.NEW_FEATURES": "New features:",
    "USER_GUIDE.WEB.PLANNING.FEAT1_1": "Drag & Drop:",
    "USER_GUIDE.WEB.PLANNING.FEAT1_2": "Assign a vehicle by dragging the request.",
    "USER_GUIDE.WEB.PLANNING.FEAT2_1": "Inbox Mode:",
    "USER_GUIDE.WEB.PLANNING.FEAT2_2": "Unread notifications take priority.",
    "USER_GUIDE.WEB.DRIVER_PLANNING.TITLE": "Driver Availability",
    "USER_GUIDE.WEB.NEW_FEATURE_TAG": "New",
    "USER_GUIDE.WEB.DRIVER_PLANNING.DESC": "A dedicated planning tool to manage drivers' working time.",
    "USER_GUIDE.WEB.DRIVER_PLANNING.BULLET1_1": "Planning:",
    "USER_GUIDE.WEB.DRIVER_PLANNING.BULLET1_2": "Add unavailability (Leave, Sick, Rest).",
    "USER_GUIDE.WEB.DRIVER_PLANNING.BULLET2_1": "Validation:",
    "USER_GUIDE.WEB.DRIVER_PLANNING.BULLET2_2": "An unavailable driver cannot be assigned.",
    "USER_GUIDE.WEB.ROADMAP.TITLE": "Vision & Security (Roadmap)",
    "USER_GUIDE.WEB.NEW_MENU_TAG": "New Menu",
    "USER_GUIDE.WEB.ROADMAP.DESC": "Full transparency on the evolution of the tool and its security.",
    "USER_GUIDE.WEB.ROADMAP.BULLET1_1": "Roadmap:",
    "USER_GUIDE.WEB.ROADMAP.BULLET1_2": "View upcoming features.",
    "USER_GUIDE.WEB.ROADMAP.BULLET2_1": "Changelog:",
    "USER_GUIDE.WEB.ROADMAP.BULLET2_2": "Update history.",
    "USER_GUIDE.WEB.ROADMAP.BULLET3_1": "Security:",
    "USER_GUIDE.WEB.ROADMAP.BULLET3_2": "Technical details (GDPR, Encryption).",
    "USER_GUIDE.WEB.ECO.TITLE": "Environmental Goals",
    "USER_GUIDE.WEB.ECO.DESC": "Track the fleet's carbon footprint.",
    "USER_GUIDE.WEB.ECO.BULLET1_1": "IAP:",
    "USER_GUIDE.WEB.ECO.BULLET1_2": "Weighted Activity Indicator.",
    "USER_GUIDE.WEB.ECO.BULLET2_1": "Action Plan:",
    "USER_GUIDE.WEB.ECO.BULLET2_2": "Monitor CO2 reduction goals.",
    "USER_GUIDE.WEB.ALERTS.TITLE": "Security Alerts",
    "USER_GUIDE.WEB.ALERTS.DESC": "Send urgent notifications (Web Push).",
    "USER_GUIDE.WEB.ALERTS.BULLET1": "Target a specific vehicle or ENTIRE FLEET.",
    "USER_GUIDE.WEB.ALERTS.BULLET2": "The driver receives the alert even if the app is closed.",
    "USER_GUIDE.WEB.VALIDATION.TITLE": "Validation & Consolidation",
    "USER_GUIDE.WEB.VALIDATION.DESC": "The validation workflow:",
    "USER_GUIDE.WEB.VALIDATION.STEP1_1": "Logistics:",
    "USER_GUIDE.WEB.VALIDATION.STEP1_2": "Checks availability.",
    "USER_GUIDE.WEB.VALIDATION.STEP2_1": "Security:",
    "USER_GUIDE.WEB.VALIDATION.STEP2_2": "Validates feasibility (Risk zones).",
    "USER_GUIDE.WEB.NEW_PROCESS": "Process Updates:",
    "USER_GUIDE.WEB.VALIDATION.NEW1_1": "Parallel Validation:",
    "USER_GUIDE.WEB.VALIDATION.NEW1_2": "Independent and simultaneous validation.",
    "USER_GUIDE.WEB.VALIDATION.NEW2_1": "Cascade Validation:",
    "USER_GUIDE.WEB.VALIDATION.NEW2_2": "Validation by lower security levels required.",
    "USER_GUIDE.WEB.VALIDATION.CONSO1": "Use",
    "USER_GUIDE.WEB.VALIDATION.CONSO2": "Consolidation",
    "USER_GUIDE.WEB.VALIDATION.CONSO3": "to group multiple requests.",
    "USER_GUIDE.WEB.MAINTENANCE.TITLE": "Fleet Management & Maintenance",
    "USER_GUIDE.WEB.MAINTENANCE.TIP_TITLE": "Notifications:",
    "USER_GUIDE.WEB.MAINTENANCE.TIP_DESC": "Automated email to supervisor if maintenance is imminent.",
    "USER_GUIDE.WEB.MAINTENANCE.BULLET1_1": "Weekly Tracking:",
    "USER_GUIDE.WEB.MAINTENANCE.BULLET1_2": "Driver checklists.",
    "USER_GUIDE.WEB.MAINTENANCE.BULLET2_1": "Configuration:",
    "USER_GUIDE.WEB.MAINTENANCE.BULLET2_2": "Define your intervals.",
    "USER_GUIDE.WEB.GENERATORS.TITLE": "Generator Maintenance",
    "USER_GUIDE.WEB.GENERATORS.DESC": "Management and tracking of the organization's generators.",
    "USER_GUIDE.WEB.GENERATORS.BULLET1_1": "Logbook:",
    "USER_GUIDE.WEB.GENERATORS.BULLET1_2": "Maintenance and breakdown logbook.",
    "USER_GUIDE.WEB.GENERATORS.BULLET2_1": "Maintenance Plan:",
    "USER_GUIDE.WEB.GENERATORS.BULLET2_2": "Tracking of run hours.",
    "USER_GUIDE.WEB.REPORTS.TITLE": "Reports & Analytics",
    "USER_GUIDE.WEB.REPORTS.DESC": "Export your monthly reports in one click.",
    "USER_GUIDE.MOBILE.TITLE": "Mobile E-Logbook (PWA)",
    "USER_GUIDE.MOBILE.OFFLINE_TITLE": "Offline Mode:",
    "USER_GUIDE.MOBILE.OFFLINE_DESC": "The application works COMPLETELY without a connection.",
    "USER_GUIDE.MOBILE.PUSH.TITLE": "Web Push Notifications",
    "USER_GUIDE.MOBILE.PUSH.DESC": "For security and responsiveness:",
    "USER_GUIDE.MOBILE.PUSH.BULLET1_1": "App Closed:",
    "USER_GUIDE.MOBILE.PUSH.BULLET1_2": "You receive alerts in the background.",
    "USER_GUIDE.MOBILE.PUSH.BULLET2_1": "Activation:",
    "USER_GUIDE.MOBILE.PUSH.BULLET2_2": "Allow notifications in the Inbox.",
    "USER_GUIDE.MOBILE.DAILY.TITLE": "Daily Use",
    "USER_GUIDE.MOBILE.DAILY.BULLET1_1": "Vehicle Selection:",
    "USER_GUIDE.MOBILE.DAILY.BULLET1_2": "Choose your vehicle at startup.",
    "USER_GUIDE.MOBILE.DAILY.BULLET2_1": "Auto GPS:",
    "USER_GUIDE.MOBILE.DAILY.BULLET2_2": "Position recording.",
    "USER_GUIDE.MOBILE.DAILY.BULLET3_1": "Free Mode:",
    "USER_GUIDE.MOBILE.DAILY.BULLET3_2": "Ad-Hoc trips without prior request.",
    "USER_GUIDE.MOBILE.INCIDENTS.TITLE": "Services & Incidents",
    "USER_GUIDE.MOBILE.INCIDENTS.BULLET1_1": "Maintenance:",
    "USER_GUIDE.MOBILE.INCIDENTS.BULLET1_2": "Check completed tasks.",
    "USER_GUIDE.MOBILE.INCIDENTS.BULLET2_1": "Incidents:",
    "USER_GUIDE.MOBILE.INCIDENTS.BULLET2_2": "Report accidents with photos.",
    "USER_GUIDE.FAQ.TITLE": "FAQ & Troubleshooting",
    "USER_GUIDE.FAQ.Q1": "Q: The PDF manual doesn't open to the right page?",
    "USER_GUIDE.FAQ.A1": "A: Check the Template configuration.",
    "USER_GUIDE.FAQ.SUPPORT": "Technical Support:",
    "USER_GUIDE.FAQ.SUPPORT_NO_EMAIL": "Please contact your local system administrator for assistance.",
    "USER_GUIDE.FOOTER": "All rights reserved"
}

# Update EN
with open('Angular/gestion-des-deplacements/src/assets/i18n/en.json', 'r', encoding='utf-8') as f:
    en = json.load(f)

for k, v in menus_en.items():
    set_nested(en, k, v)
for k, v in guide_en.items():
    set_nested(en, k, v)

with open('Angular/gestion-des-deplacements/src/assets/i18n/en.json', 'w', encoding='utf-8') as f:
    json.dump(en, f, indent=4, ensure_ascii=False)

# Update FR
with open('Angular/gestion-des-deplacements/src/assets/i18n/fr.json', 'r', encoding='utf-8') as f:
    fr = json.load(f)

for k, v in menus_fr.items():
    set_nested(fr, k, v)
for k, v in guide_fr.items():
    set_nested(fr, k, v)

with open('Angular/gestion-des-deplacements/src/assets/i18n/fr.json', 'w', encoding='utf-8') as f:
    json.dump(fr, f, indent=4, ensure_ascii=False)

print("Menus and Guide translation sync complete!")
